// MFCExampleCode.idl : type library source for MFC-Example-Code.exe

// This file will be processed by the MIDL compiler to produce the
// type library (MFCExampleCode.tlb).

[ uuid(2448A547-EC16-4036-B419-33675184923F), version(1.0) ]
library MFCExampleCode
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  Primary dispatch interface for CMFCExampleCodeDoc
	
	[ uuid(FFD422F2-4B62-4D59-B35A-8CACEE5806CB) ]
	dispinterface IMFCExampleCode
	{
		properties:
			
		methods:
	};

	//  Class information for CMFCExampleCodeDoc
	
	[ uuid(E858A01C-0C76-41E6-A375-C1626C6E0F8C) ]
	coclass MFCExampleCode
	{
		[default] dispinterface IMFCExampleCode;
	};
};
