// MFCExampleSnippets.idl : type library source for MFC-Example-Snippets.exe

// typedefs for remotable data types:
import "wtypes.idl";

// core type interfaces:
import "unknwn.idl";

// core infrastructure itfs
import "objidl.idl";

// ole itfs
import "oleidl.idl";

// automation itfs
import "oaidl.idl";

// ActiveX Control itfs
import "ocidl.idl";

[
	uuid(2448A547-EC16-4036-B419-33675184923F),
	version(1.0)
]
library MFCExampleSnippets
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");



	[
		uuid(FFD422F2-4B62-4D59-B35A-8CACEE5806CB)
	]
	dispinterface IMFCExampleSnippets
	{
	  properties:

	  methods:
	};



	[
		uuid(E858A01C-0C76-41E6-A375-C1626C6E0F8C)
	]
	coclass MFCExampleSnippets
	{
		[default] dispinterface IMFCExampleSnippets;
	};
};
